### ISSUE TITLE
Documentation non-existent

### ISSUE THREAD

**Issue by KianTanner** [mayaam/Zombie-survival#1]
No comments at all
Readme is adequate

**Comment by mayaam** [comment]
Hey thanks. I fixed it. It's fully documented now. Please let me know if it needs more clarification or if I should do anything different! I'm not very used to commenting my programs.

**Comment by KianTanner** [comment]
Yeah, it looks good now. I understand not commenting stuff, it took a while for me to get in the habit of doing it. I just didn't want you to get marked down for it.

**Comment by mayaam** [comment]
mhhm I appreciate it!
